server.port=9090

# Ruta para Usuarios
spring.cloud.gateway.routes[0].id=usuarios-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/usuarios/**

# Ruta para Reportes
spring.cloud.gateway.routes[1].id=reportes-service
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/reportes/**